// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PatientSurvey.AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SurveyResultsFeature : Xunit.IUseFixture<SurveyResultsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SurveyResults.feature"
#line hidden
        
        public SurveyResultsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SurveyResults", "As a member of the public\r\nI want to be able to view a list of hospitals\r\nSo that" +
                    " I can see which hospitals are included in the study.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name",
                        "Hospital",
                        "Pre-surgery health score",
                        "3 months Post-surgery health score",
                        "6 months Post-surgery health score",
                        "Overall rating of the care received"});
            table1.AddRow(new string[] {
                        "Patient",
                        "One",
                        "A",
                        "4/10",
                        "4/10",
                        "7/10",
                        "8/10"});
            table1.AddRow(new string[] {
                        "Patient",
                        "Two",
                        "B",
                        "6/10",
                        "5/10",
                        "5/10",
                        "6/10"});
            table1.AddRow(new string[] {
                        "Patient",
                        "Three",
                        "A",
                        "2/10",
                        "5/10",
                        "6/10",
                        "9/10"});
#line 7
 testRunner.Given("the following survey data:", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        public virtual void SetFixture(SurveyResultsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "SurveyResults")]
        [Xunit.TraitAttribute("Description", "Retrieve a list of hospitals")]
        public virtual void RetrieveAListOfHospitals()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve a list of hospitals", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 14
 testRunner.When("I view the hospital list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("hospitals \'A,B\' should be in the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SurveyResultsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SurveyResultsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
